In [2]:
import pandas as pd

In [3]:
df_cust = pd.read_csv('data/customers.csv')
df_cust.shape

(1000, 8)

In [5]:
df_ca = pd.read_csv('data/credit_profiles.csv')
df_ca.shape

(1004, 6)

In [6]:
df_trans = pd.read_csv("data/transactions.csv")
df_trans.shape

(500000, 7)

In [8]:
import mysql.connector as mc

In [11]:
conn = mc.connect(
    host = "localhost",
    user = "root",
    passwd = "Pass@123",
    database = "e_master_card"
)

In [12]:
df_cust = pd.read_sql("SELECT * FROM customers", conn)
df_cust.head()

C:\Users\vaibh\AppData\Local\Temp\ipykernel_17872\1487446849.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_cust = pd.read_sql("SELECT * FROM customers", conn)

,cust_id,name,gender,age,location,occupation,annual_income,marital_status
0,1,Manya Acharya,Female,2,City,Business Owner,358211,Married
1,2,Anjali Pandey,Female,47,City,Consultant,65172,Single
2,3,Aaryan Chauhan,Male,21,City,Freelancer,22378,Married
3,4,Rudra Bali,Male,24,Rural,Freelancer,33563,Married
4,5,Advait Malik,Male,48,City,Consultant,39406,Married

In [13]:
df_trans = pd.read_sql("SELECT * FROM transactions", conn)
df_trans.head()

C:\Users\vaibh\AppData\Local\Temp\ipykernel_17872\90138623.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_trans = pd.read_sql("SELECT * FROM transactions", conn)

,tran_id,cust_id,tran_date,tran_amount,platform,product_category,payment_type
0,1,705,2023-01-01,63,Flipkart,Electronics,Phonepe
1,2,385,2023-01-01,99,Alibaba,Fashion & Apparel,Credit Card
2,3,924,2023-01-01,471,Shopify,Sports,Phonepe
3,4,797,2023-01-01,33,Shopify,Fashion & Apparel,Gpay
4,5,482,2023-01-01,68,Amazon,Fashion & Apparel,Net Banking

In [14]:
df_cs = pd.read_sql("SELECT * FROM credit_profiles", conn)
df_cs.head()

C:\Users\vaibh\AppData\Local\Temp\ipykernel_17872\1858606683.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_cs = pd.read_sql("SELECT * FROM credit_profiles", conn)

,cust_id,credit_score,credit_utilisation,outstanding_debt,credit_inquiries_last_6_months,credit_limit
0,1,749,0.585171,19571.0,0.0,40000.0
1,2,587,0.107928,161644.0,2.0,1250.0
2,3,544,0.854807,513.0,4.0,1000.0
3,4,504,0.336938,224.0,2.0,1000.0
4,5,708,0.586151,18090.0,2.0,40000.0

In [15]:
df_cust.describe()

           cust_id          age  annual_income
count  1000.000000  1000.000000    1000.000000
mean    500.500000    36.405000  132439.799000
std     288.819436    15.666155  113706.313793
min       1.000000     1.000000       0.000000
25%     250.750000    26.000000   42229.750000
50%     500.500000    32.000000  107275.000000
75%     750.250000    46.000000  189687.500000
max    1000.000000   135.000000  449346.000000

In [16]:
df_cust.isnull().sum()

cust_id           0
name              0
gender            0
age               0
location          0
occupation        0
annual_income     0
marital_status    0
dtype: int64

In [18]:
occ_wise_inc_median = df_cust.groupby('occupation')['annual_income'].median()
occ_wise_inc_median

occupation
Accountant              65265.0
Artist                  44915.0
Business Owner         254881.0
Consultant              51175.0
Data Scientist         127889.0
Freelancer              45189.5
Fullstack Developer     74457.0
Name: annual_income, dtype: float64