In [13]:
import pandas as pd
df = pd.read_csv("car_ownership.csv")
df.head()

   monthly_salary  owns_car
0           22000         0
1           25000         0
2           47000         1
3           52000         0
4           46000         1

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X = df[['monthly_salary']]
y = df['owns_car']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.8888888888888888

In [15]:
X_test

    monthly_salary
8            62000
13           29000
9            61000
21           26000
0            22000
11           28000
16           25000
17           58000
12           27000

In [16]:
y_test

8     1
13    0
9     1
21    0
0     0
11    0
16    1
17    1
12    0
Name: owns_car, dtype: int64

In [17]:
y_test.tolist()

[1, 0, 1, 0, 0, 0, 1, 1, 0]

In [22]:
y_pred = model.predict(X_test)
y_pred

array([1, 0, 1, 0, 0, 0, 0, 1, 0])

In [19]:
model.predict_proba(X_test)

array([[0.04530932, 0.95469068],
       [0.80955349, 0.19044651],
       [0.05158003, 0.94841997],
       [0.86480041, 0.13519959],
       [0.91687254, 0.08312746],
       [0.82967465, 0.17032535],
       [0.87995016, 0.12004984],
       [0.07564619, 0.92435381],
       [0.84806892, 0.15193108]])

In [20]:
# accuracy = right_prediction / total_prediction

In [21]:
from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.83      1.00      0.91         5
           1       1.00      0.75      0.86         4

    accuracy                           0.89         9
   macro avg       0.92      0.88      0.88         9
weighted avg       0.91      0.89      0.89         9