In [1]:
print("Hi")

Hi

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("Height main data.csv")
df.head(2)

  Name  Height
0    A     1.2
1    B     4.6

In [9]:
Q1, Q3 = df.Height.quantile([0.25, 0.75])
round(Q1,2), round(Q3,2)

(5.35, 6.28)

In [12]:
IQR = round(Q3-Q1, 3)
IQR

0.925

In [14]:
lower_limit = round(Q1 - IQR * 1.5, 3)
upper_limit = round(Q3 + IQR * 1.5, 3)
lower_limit, upper_limit

(3.963, 7.663)

In [15]:
df_new = df[(df.Height > lower_limit) & (df.Height < upper_limit)]
df_new

   Name  Height
1     B     4.6
2     C     4.9
3     D     5.1
4     E     5.2
5     F     5.4
6     G     5.5
7     H     5.5
8     I     5.6
9     J     5.6
10    K     5.8
11    L     5.9
12    M     6.0
13    N     6.1
14    O     6.2
15    P     6.5
16    Q     6.6
17    R     7.1
18    S     7.1