<h3 align="center"> ML Course: Randomized Search CV</h3>

We will generate a synthetic dataset

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

X, y = make_classification(
    n_features=10, 
    n_samples=1000, 
    n_informative=8,
    n_redundant=2,
    n_repeated=0,
    n_classes=2, 
    random_state=42
)

### GridSearchCV

In [5]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
clf = GridSearchCV(
    DecisionTreeClassifier(),
    {'criterion': ["gini", "entropy"],'max_depth': [5, 10, 15, 20]},
    cv=5,
    return_train_score=False
)
clf.fit(X, y)
df = pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002604,0.000372,0.000603,0.000492,gini,5,"{'criterion': 'gini', 'max_depth': 5}",0.775,0.795,0.740,0.795,0.765,0.774,0.020591,8
1,0.003406,0.000377,0.000400,0.000490,gini,10,"{'criterion': 'gini', 'max_depth': 10}",0.775,0.735,0.820,0.795,0.805,0.786,0.029394,6
2,0.003409,0.000380,0.000501,0.000634,gini,15,"{'criterion': 'gini', 'max_depth': 15}",0.795,0.710,0.800,0.825,0.825,0.791,0.042356,4
3,0.003605,0.000375,0.000401,0.000491,gini,20,"{'criterion': 'gini', 'max_depth': 20}",0.800,0.740,0.800,0.790,0.820,0.790,0.026833,5
4,0.004102,0.000205,0.000942,0.000219,entropy,5,"{'criterion': 'entropy', 'max_depth': 5}",0.765,0.785,0.745,0.810,0.790,0.779,0.022226,7
5,0.005104,0.000580,0.000803,0.000401,entropy,10,"{'criterion': 'entropy', 'max_depth': 10}",0.770,0.795,0.840,0.780,0.800,0.797,0.024000,3
6,0.005928,0.000562,0.000798,0.000399,entropy,15,"{'criterion': 'entropy', 'max_depth': 15}",0.765,0.800,0.835,0.805,0.860,0.813,0.032342,2
7,0.005725,0.000230,0.000201,0.000401,entropy,20,"{'criterion': 'entropy', 'max_depth': 20}",0.775,0.810,0.840,0.805,0.845,0.815,0.025495,1

### RandomizedSearchCV

Use RandomizedSearchCV to reduce number of iterations and with random combination of parameters. This is useful when you have too many parameters to try and your training time is longer. It helps reduce the cost of computation

In [6]:
from sklearn.model_selection import RandomizedSearchCV

clf = RandomizedSearchCV(
    DecisionTreeClassifier(),
    {'criterion': ["gini", "entropy"],'max_depth': [5, 10, 15, 20]},
    cv=5,
    return_train_score=False,
    n_iter=3 
)
clf.fit(X, y)
df = pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_criterion,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007056,0.000789,0.001031,0.000635,20,entropy,"{'max_depth': 20, 'criterion': 'entropy'}",0.755,0.800,0.830,0.800,0.845,0.806,0.030887,1
1,0.004604,0.000637,0.001171,0.000667,5,entropy,"{'max_depth': 5, 'criterion': 'entropy'}",0.765,0.780,0.755,0.815,0.775,0.778,0.020396,3
2,0.005708,0.000681,0.000807,0.000513,10,entropy,"{'max_depth': 10, 'criterion': 'entropy'}",0.770,0.795,0.820,0.785,0.795,0.793,0.016310,2

In [7]:
clf.best_params_

{'max_depth': 20, 'criterion': 'entropy'}